# This exercise aims to introduce you to a very basic concept of hashing algorithms, how they work, why they are useful and what are their weaknesses. And along the way you'll pick up the principle behind the flaw of hashing functions.
# Do you remember at some lesson I explained to you about the birthday paradox that was used creating birthday attack. Now you're gone make the birthday attack with the md5 hashing algorithm. Your task ahead is to find collisions for this algorithm, (only for the first 40 bits of the hash, aka first 10 hex characters).
# You have to write a small program that would eventually find a collision for the first 40 bits generated by the md5 algorithm.

